config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :events
  resources :event_details, path: '/event-details'
  get 'about', to: 'home#about'

  resources :users
  resources :participants

  get 'verify-email', to: 'users#verify'
  get 'resend-verification', to: 'users#resend_verification'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'create-account', to: 'users#new'
  get 'welcome', to: 'users#welcome'
  get 'reset-password', to: 'users#reset_load'
  post 'reset-password', to: 'users#reset_confirm'
  post 'reset-password-save', to: 'users#reset_save'
  get 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    skip_before_action :authorized, only: %i[index about]
    layout 'home', only: %i[index]

    def index; end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="py-5 text-white" style="background-color: #ff6600;">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="display-5">Run. Climb. Crawl. Volunteer.</h1>
            <h1>Track your OCRs with MudTrackr.</h1>
        </div>
    </div>
    <div class="row py-3">
        <div class="col gap-3 d-flex justify-content-center">
            <%= link_to 'Create Account', '/create-account', class: 'btn btn-outline-light btn-lg' %>
            <%= link_to 'Login', '/login', class: 'btn btn-light btn-lg' %>
        </div>
    </div>
    <div class="row pt-4 justify-content-center align-items-center text-center">
        <div class="col-12 col-sm-6 col-md-3 order-3 order-md-1 pt-3">
            <div class="card border-0 bg-transparent">
                <div class="card-img-top">
                    <i class="bi bi-award display-1"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Track your challenges</h5>
                    <p class="card-text">Compete in a virtual event or challenge? See your effort and hard-earned badges here.</p>
                    <a href="#" class="btn btn-outline-light">Coming Soon!</a>
                </div>
            </div>
        </div>
        <div class="col-12 order-2 d-sm-none">
            <hr class="border-white">
        </div>
        <div class="col-12 col-sm-12 col-md-4 order-1 order-md-2 pt-3">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-12 mx-auto">
                    <div class="card border-0 bg-transparent">
                        <div class="card-img-top">
                            <i class="bi bi-trophy display-1"></i>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">Keep track of your events</h5>
                            <p class="card-text">Whether it's a Tough Mudder, Spartan, Savage Race, or another OCR, keep track of which ones you've participated in, and add any competitive results to see how you stack up. Don't see your event here? Submit it and we'll get it added so you can see all your data.</p>
                            <%= link_to 'Events', events_path, class: 'btn btn-outline-light' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 order-4 d-sm-none">
            <hr class="border-white">
        </div>
        <div class="col-12 col-sm-6 col-md-3 order-5 order-md-3 pt-3">
            <div class="card border-0 bg-transparent">
                <div class="card-img-top">
                    <i class="bi bi-people display-1"></i>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Track volunteer hours</h5>
                    <p class="card-text">Enjoy discounts? Track your volunteer shifts and show how many hours you've given back.</p>
                    <a href="#" class="btn btn-outline-light">Coming Soon!</a>
                </div>
            </div>
        </div>
    </div>
</div>