config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :events
  resources :event_details, path: '/event-details'
  get 'about', to: 'home#about'

  resources :users
  resources :participants

  get 'verify-email', to: 'users#verify'
  get 'resend-verification', to: 'users#resend_verification'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'create-account', to: 'users#new'
  get 'welcome', to: 'users#welcome'
  get 'reset-password', to: 'users#reset_load'
  post 'reset-password', to: 'users#reset_confirm'
  post 'reset-password-save', to: 'users#reset_save'
  get 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    # Helpful for understanding how to relate foreign keys: https://stackoverflow.com/questions/13867587/getting-a-value-from-a-table-through-a-foreign-key-in-rails
    belongs_to :brand, class_name: 'Brand', foreign_key: 'brand_id'

    belongs_to :created_by, :class_name => 'User', :foreign_key => 'created_by'
    belongs_to :approved_by, :class_name => 'User', :foreign_key => 'approved_by', optional: true
    belongs_to :updated_by, :class_name => 'User', :foreign_key => 'updated_by'
end

app/models/event_type.rb
class EventType < ApplicationRecord
    belongs_to :brand, :class_name => 'Brand', :foreign_key => 'brand_id'
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController

	skip_before_action :authorized, only: %i[index show]

	def can_edit_event(event)
		logged_in? && admin? && !event.archived
	end

    def index
        @events = Event.where(archived: false).order(date: :desc)
        @event_years = @events.select(:date).map { |event| event.date.year }.uniq
        @event_brands = @events.includes(:brand).map(&:brand).uniq.sort!
    end

  def create
    @event = Event.new(event_params)
    @event.created_by = current_user
    @event.updated_by = current_user
    if @event.save
      redirect_to @event
    else
      render :'common/error'
    end
  end

	def show
		@event = Event.find(params[:id])
		@can_edit_event = can_edit_event(@event)
		@event_details = EventDetail.includes(:event_type).where(event_id: params[:id]).order(Arel.sql('event_types.display_order ASC'))
		@new_event_detail = EventDetail.new
		@participants = Participant.includes([{ event_detail: [:event_type] }, :user]).where(event_detail: { event_id: params[:id] }).order(Arel.sql('event_types.display_order'), Arel.sql('participants.participation_day'), Arel.sql('users.last_name'))
		if logged_in?
			@user_list = User.where(id: current_user.id)
			@event_types = EventType.where(brand_id: @event.brand_id).order(display_order: :asc)
		end
		@new_participant = Participant.new
		@new_participant.event_detail = EventDetail.new
		@active_tab = 'details'
		@active_tab = params['tab'] unless params['tab'].nil?
	end

  def edit
    @event = Event.find(params[:id])
  end

	def update
		@event = Event.find(params[:id])
		unless can_edit_event(@event)
			respond_to do |format|
				format.html { render :'common/unauthorized' }
				format.json { render json: { message: 'Insufficient privileges' }, status: :forbidden }
			end && return
		end

		if @event.update(event_params.merge(updated_by: current_user))
			redirect_to @event
		else
			render :'common/error'
		end
	end

  def destroy
    @event = Event.find(params[:id])
    @event.archived = true
    @event.updated_by = current_user
    if @event.save
      redirect_to events_path
    else
      render :'common/error'
    end
  end

	private

	def event_params
		params.require(:event).permit(:name, :brand_id, :address, :city, :state, :country, :date)
	end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%
    breadcrumb_items = [
        {
            url: events_path,
            text: 'Events'
        },
        {
            url: event_path(@event),
            text: @event.name
        },
        {
            text: 'Edit'
        }
    ]
%>
<%= render partial: 'common/breadcrumb', locals: { items: breadcrumb_items } %>
<div class="row justify-content-center">
    <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
        <%= form_with model: @event do |form| %>
            <div class="row pt-4 gx-2">
                <div class="col-6">
                    <%= form.submit 'Save', :disabled => @event.archived, :class => 'btn btn-primary btn-lg w-100' %>
                </div>
                <% if !@event.archived %>
                <div class="col-6">
                    <button type="button" class="btn btn-danger btn-lg w-100" data-bs-toggle="modal" data-bs-target="#deleteEventModal">Remove Event</button>
                </div>
                <% end %>
            </div>
            <fieldset <% if @event.archived %>disabled<% end %>>
                <div class="row pt-4 gx-2 gy-3">
                    <div class="col-12">
                        <%= form.label :name, 'Event Name', { class: 'form-label' } %>
                        <%= form.text_field :name, { class: 'form-control' } %>
                    </div>
                    <div class="col-12">
                        <%= form.label :address, 'Address', { class: 'form-label' } %>
                        <%= form.text_field :address, { class: 'form-control' } %>
                    </div>
                    <div class="col-6">
                        <%= form.label :city, 'City', { class: 'form-label' } %>
                        <%= form.text_field :city, { class: 'form-control' } %>
                    </div>
                    <div class="col-3">
                        <%= form.label :state, 'State', { class: 'form-label' } %>
                        <%= form.select :state, Rails.configuration.state_list, { prompt: 'Select...' }, { class: 'form-select' } %>
                    </div>
                    <div class="col-3">
                        <%= form.label :country, 'Country', { class: 'form-label' } %>
                        <%= form.select :country, Rails.configuration.country_list, { prompt: 'Select...' }, { class: 'form-select' } %>
                    </div>
                    <div class="col-6">
                        <%= form.label :date, 'Date', { class: 'form-label' } %>
                        <%= form.date_field :date, { class: 'form-control' } %>
                    </div>
                </div>
            </fieldset>
        <% end %>
        <div class="row pt-3">
            <div class="col-12">
                <small>Last updated: <%= @event.updated_by.full_name %>, <%= @event.updated_at.strftime('%D %r') %></small>
            </div>
        </div>
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteEventModal" tabindex="-1" role="dialog" aria-labelledby="deleteEventModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteEventModalLabel">Delete <%= @event.name %></h5>
                <%= dismiss_modal_tag %>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this event?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <%= link_to 'Delete', event_path(@event), method: :delete, class: 'btn btn-danger' %>
            </div>
        </div>
    </div>
</div>

app/views/events/index.html.erb
<h1>Events</h1>

<% if logged_in? %>
<div class="row pt-3">
    <div class="col-8 col-sm-6 col-md-5 col-lg-4 mx-auto">
        <%= button_tag 'New Event',
            type: 'button',
            class: 'btn btn-primary btn-lg col-12',
            data: {
                bs_toggle: 'modal',
                bs_target: '#createEventModal'
            } %>
    </div>
</div>
<% end %>

<div class="row pt-3">
    <div class="col-12 col-md-10 col-xl-8 mx-auto">
        <div class="row gx-1">
            <div class="col-2 col-lg-1">
                <button type="button" class="w-100 btn btn-outline-primary btn-sm rounded-3 event-filter-year active" value="" data-bs-toggle="button">All</button>
            </div>
          <% @event_years.each do |year| %>
            <div class="col-2 col-lg-1">
                <button type="button" class="w-100 btn btn-outline-primary btn-sm rounded-3 event-filter-year" value="<%= year %>" data-bs-toggle="button"><%= year %></button>
            </div>
          <% end %>
        </div>
    </div>
</div>

<div class="row pt-3">
    <div class="col-12 col-md-10 col-xl-8 mx-auto">
        <div class="row gx-1">
            <div class="col-4 col-md-3 col-lg-2">
                <button type="button" class="w-100 btn btn-outline-primary btn-sm rounded-3 event-filter-brand active" value="" data-bs-toggle="button">All</button>
            </div>
          <% @event_brands.each do |brand| %>
            <div class="col-4 col-md-3 col-lg-2">
                <button type="button" class="w-100 btn btn-outline-primary btn-sm rounded-3 event-filter-brand" value="<%= brand.id %>" data-bs-toggle="button"><%= brand.name %></button>
            </div>
          <% end %>
        </div>
    </div>
</div>

<div class="row pt-3">
    <div class="col-12 col-md-10 col-xl-8 mx-auto">
        <table id="events-table" class="table table-sm table-striped table-hover data-table w-100" style="font-size: 14px;">
            <thead>
                <tr>
                    <th>Event Name</th>
                    <th class="d-none d-md-table-cell">Location</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                <% @events.each do |event| %>
                <tr class="table-row clickable-row" data-href="<%= event_path(event) %>">
                    <td data-search="<%= event.brand_id %>"><%= event.name %></td>
                    <td class="d-none d-md-table-cell"><%= "#{event.city}, #{event.state}" %>
                    <td data-sort="<%= event.date.strftime('%Y%m%d') %>" data-search="<%= event.date.strftime('%Y%m%d') %>"><%= event.date.nil? ? '' : event.date.strftime('%b %-d, %Y') %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<% if logged_in? %>
<!-- Create Event Modal -->
<div class="modal fade" id="createEventModal" tabindex="-1" role="dialog" aria-labelledby="createEventModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <%= form_with model: Event.new do |form| %>
                <div class="modal-header">
                    <h5 class="modal-title" id="createEventModalLabel">Create New Event</h5>
                    <%= dismiss_modal_tag %>
                </div>
                <div class="modal-body">
                    <div class="row pt-2 gx-2 gy-3">
                        <div class="col-12">
                            <div class="row align-items-center">
                                <% Brand.order(:id).each do |brand| %>
                                <div class="col-4">
                                    <div class="brand-logo p-1 rounded h-100">
                                        <% if brand.logo_path.nil? %>
                                        <div class="text-center"><%= brand.name %></div>
                                        <% else %>
                                        <%= image_tag brand.logo_path, class: "img-fluid" %>
                                        <% end %>
                                        <input class="d-none" type="radio" value="<%= brand.id %>" name="event[brand_id]" id="event_brand_id_<%= brand.id %>">
                                    </div>
                                </div>
                                <% end %>
                            </div>
                        </div>
                        <div class="col-12">
                            <%= form.label :name, 'Event Name', { class: 'form-label' } %>
                            <%= form.text_field :name, { class: 'form-control' } %>
                        </div>
                        <div class="col-12">
                            <%= form.label :address, 'Address', { class: 'form-label' } %>
                            <%= form.text_field :address, { class: 'form-control' } %>
                        </div>
                        <div class="col-6">
                            <%= form.label :city, 'City', { class: 'form-label' } %>
                            <%= form.text_field :city, { class: 'form-control' } %>
                        </div>
                        <div class="col-3">
                            <%= form.label :state, 'State', { class: 'form-label' } %>
                            <%= form.select :state, Rails.configuration.state_list, { prompt: 'Select...' }, { class: 'form-select' } %>
                        </div>
                        <div class="col-3">
                            <%= form.label :country, 'Country', { class: 'form-label' } %>
                            <%= form.select :country, Rails.configuration.country_list, { prompt: 'Select...' }, { class: 'form-select' } %>
                        </div>
                        <div class="col-6">
                            <%= form.label :date, 'Date', { class: 'form-label' } %>
                            <%= form.date_field :date, { class: 'form-control' } %>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <%= form.submit 'Create', :class => 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/events/show.html.erb
<%
    breadcrumb_items = [
        {
            :url => '/events',
            :text => 'Events'
        },
        {
            :text => @event.name
        }
    ]
%>
<%= render partial: 'common/breadcrumb', locals: { items: breadcrumb_items } %>
<div class="row">
    <div class="col-12">
        <p>
            <span class="h3"><%= @event.name %></span>
            <% if @can_edit_event %>
            <span class="ps-3"><%= link_to "Edit", edit_event_path(@event) %></span>
            <% end %>
        </p>
    </div>
</div>
<div class="row pt-3">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <ul class="nav nav-tabs" id="event-tabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link <%= @active_tab == 'details' ? 'active' : nil %>" id="details-tab" data-bs-toggle="tab" data-bs-target="#details-content" type="button" role="tab" aria-controls="details-tab" aria-selected="<%= @active_tab == 'details' ? 'true' : 'false' %>">Details</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link <%= @active_tab == 'event-types' ? 'active' : nil %>" id="event-types-tab" data-bs-toggle="tab" data-bs-target="#event-types-content" type="button" role="tab" aria-controls="event-types-tab" aria-selected="<%= @active_tab == 'event-types' ? 'true' : 'false' %>">Event Types</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link <%= @active_tab == 'participants' ? 'active' : nil %>" id="participants-tab" data-bs-toggle="tab" data-bs-target="#participants-content" type="button" role="tab" aria-controls="participants-tab" aria-selected="<%= @active_tab == 'participants' ? 'true' : 'false' %>">Participants</button>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row pt-3 justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="tab-content" id="tab-content">
                    <div class="tab-pane fade <%= (@active_tab == nil || @active_tab == 'details') ? 'show active' : nil %>" id="details-content" role="tabpanel" aria-labelledby="details-tab">
                        <%= render 'events/partials/details', locals: { event: @event } %>
                    </div>
                    <div class="tab-pane fade <%= @active_tab == 'event-types' ? 'show active' : nil %>" id="event-types-content" role="tabpanel" aria-labelledby="event-types-tab">
                        <%= render 'events/partials/event_details', locals: { event_details: @event_details } %>
                    </div>
                    <div class="tab-pane fade <%= @active_tab == 'participants' ? 'show active' : nil %>" id="participants-content" role="tabpanel" aria-labelledby="participants-tab">
                        <%= render 'events/partials/participants', locals: { event: @event, participants: @participants } %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>